name: "hello world wprkflow"

on:
  push:
    branches:
      -master
      -production

jobs:
  hello_world:
    runs_on: ubuntu_latest
    steps:
      -name: "print hello world"
       run: echo "my name is abhishek"

