name: "multi event pipeline/workflow"

on:
  push:
    branches:
      - master
      - main

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on push to master or main"
        run: echo "My name is Abhishek"
